language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_install:
  - npm ci
script:
  - npm run test
deploy:
  provider: npm
  email: "YOUR_EMAIL_ADDRESS"
  api_key: "YOUR_AUTH_TOKEN"
on:
  branch: master
